//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumption
    {
        public int id { get; set; }
        public int idGroup { get; set; }
        public int idPlan { get; set; }
        public double consumptionAzure { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public bool status { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
