//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_medIAEntities : DbContext
    {
        public DB_medIAEntities()
            : base("name=DB_medIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Consumption> Consumptions { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<License> Licenses { get; set; }
        public virtual DbSet<Period> Periods { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<Plan_Product> Plan_Product { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Role_Permission> Role_Permission { get; set; }
        public virtual DbSet<Sector> Sectors { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Group_Term> Group_Term { get; set; }
        public virtual DbSet<KeyPhrase> KeyPhrases { get; set; }
        public virtual DbSet<Opinion> Opinions { get; set; }
        public virtual DbSet<OpinionLimit> OpinionLimits { get; set; }
        public virtual DbSet<Publisher> Publishers { get; set; }
        public virtual DbSet<Publisher_State> Publisher_State { get; set; }
        public virtual DbSet<PublisherType> PublisherTypes { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TermToSearch> TermToSearches { get; set; }
        public virtual DbSet<User_Video> User_Video { get; set; }
        public virtual DbSet<Video_TermToSearch> Video_TermToSearch { get; set; }
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Favorite_News> Favorite_News { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Mention> Mentions { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<News_About> News_About { get; set; }
        public virtual DbSet<News_KeyPhrase> News_KeyPhrase { get; set; }
        public virtual DbSet<News_Mention> News_Mention { get; set; }
        public virtual DbSet<News_Publisher> News_Publisher { get; set; }
        public virtual DbSet<News_TermToSearch> News_TermToSearch { get; set; }
        public virtual DbSet<News_Video> News_Video { get; set; }
        public virtual DbSet<Favorite_Tweet> Favorite_Tweet { get; set; }
        public virtual DbSet<ssas_jobs> ssas_jobs { get; set; }
        public virtual DbSet<tweets_normalized> tweets_normalized { get; set; }
        public virtual DbSet<tweets_processed> tweets_processed { get; set; }
        public virtual DbSet<twitter_query> twitter_query { get; set; }
        public virtual DbSet<twitter_query_details> twitter_query_details { get; set; }
        public virtual DbSet<twitter_query_readable> twitter_query_readable { get; set; }
        public virtual DbSet<Creator> Creators { get; set; }
        public virtual DbSet<EncodingFormat> EncodingFormats { get; set; }
        public virtual DbSet<Favorite_Video> Favorite_Video { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<Video_KeyPhrase> Video_KeyPhrase { get; set; }
        public virtual DbSet<Video_Opinion> Video_Opinion { get; set; }
        public virtual DbSet<VideoIndexer> VideoIndexers { get; set; }
        public virtual DbSet<configuration> configurations { get; set; }
        public virtual DbSet<minimum_tweets> minimum_tweets { get; set; }
        public virtual DbSet<vw_Fuente> vw_Fuente { get; set; }
        public virtual DbSet<vw_Group_Term> vw_Group_Term { get; set; }
        public virtual DbSet<vw_HistogramOpinions> vw_HistogramOpinions { get; set; }
        public virtual DbSet<vw_KeyPhrase> vw_KeyPhrase { get; set; }
        public virtual DbSet<vw_news> vw_news { get; set; }
        public virtual DbSet<vw_User_Video> vw_User_Video { get; set; }
        public virtual DbSet<vw_Video> vw_Video { get; set; }
        public virtual DbSet<vw_configuration> vw_configuration { get; set; }
        public virtual DbSet<vw_minimum_tweets> vw_minimum_tweets { get; set; }
        public virtual DbSet<vw_tweets_normalized> vw_tweets_normalized { get; set; }
        public virtual DbSet<vw_tweets_processed> vw_tweets_processed { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
