//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite_Tweet
    {
        public int id { get; set; }
        public int idTweet { get; set; }
        public int idUser { get; set; }
        public bool status { get; set; }
    }
}
