//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.Favorite_News = new HashSet<Favorite_News>();
            this.Images = new HashSet<Image>();
            this.News_About = new HashSet<News_About>();
            this.News_KeyPhrase = new HashSet<News_KeyPhrase>();
            this.News_Mention = new HashSet<News_Mention>();
            this.News_Publisher = new HashSet<News_Publisher>();
            this.News_TermToSearch = new HashSet<News_TermToSearch>();
            this.News_Video = new HashSet<News_Video>();
        }
    
        public int id { get; set; }
        public Nullable<int> idCategory { get; set; }
        public Nullable<System.DateTime> datePublished { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public string description { get; set; }
        public string text { get; set; }
        public bool status { get; set; }
        public Nullable<int> idOpinion { get; set; }
    
        public virtual Opinion Opinion { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite_News> Favorite_News { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News_About> News_About { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News_KeyPhrase> News_KeyPhrase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News_Mention> News_Mention { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News_Publisher> News_Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News_TermToSearch> News_TermToSearch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News_Video> News_Video { get; set; }
    }
}
