//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_Product
    {
        public int id { get; set; }
        public int idPlan { get; set; }
        public int idProduct { get; set; }
        public bool status { get; set; }
    
        public virtual Plan Plan { get; set; }
        public virtual Product Product { get; set; }
    }
}
