//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Plan_Product = new HashSet<Plan_Product>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string level { get; set; }
        public double price { get; set; }
        public int transactionsAllowed { get; set; }
        public string url { get; set; }
        public string urlDocumentation { get; set; }
        public System.DateTime expirationDate { get; set; }
        public bool status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan_Product> Plan_Product { get; set; }
    }
}
