//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publisher_State
    {
        public int id { get; set; }
        public int idPublisher { get; set; }
        public int idState { get; set; }
    
        public virtual Publisher Publisher { get; set; }
        public virtual State State { get; set; }
    }
}
