//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tweets_processed
    {
        public string tweetid { get; set; }
        public Nullable<System.DateTime> dateorig { get; set; }
        public Nullable<System.DateTime> hourofdate { get; set; }
        public Nullable<System.DateTime> minuteofdate { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string masterid { get; set; }
        public string retweet { get; set; }
        public string username { get; set; }
        public string userlocation { get; set; }
        public string usernumber { get; set; }
        public string image_url { get; set; }
        public string authorimage_url { get; set; }
        public string direction { get; set; }
        public Nullable<int> favorited { get; set; }
        public Nullable<int> user_followers { get; set; }
        public Nullable<int> user_friends { get; set; }
        public Nullable<int> user_favorites { get; set; }
        public Nullable<int> user_totaltweets { get; set; }
    
        public virtual tweets_normalized tweets_normalized { get; set; }
    }
}
