//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tweets_normalized
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tweets_normalized()
        {
            this.tweets_processed = new HashSet<tweets_processed>();
        }
    
        public string masterid { get; set; }
        public Nullable<int> mentions { get; set; }
        public Nullable<int> hashtags { get; set; }
        public string tweet { get; set; }
        public string twitterhandle { get; set; }
        public string userlocation { get; set; }
        public string usernumber { get; set; }
        public Nullable<double> sentiment { get; set; }
        public Nullable<double> sentimentbin { get; set; }
        public string sentimentposneg { get; set; }
        public string lang { get; set; }
        public string accounttag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tweets_processed> tweets_processed { get; set; }
    }
}
