//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Favorite_News = new HashSet<Favorite_News>();
            this.Favorite_Video = new HashSet<Favorite_Video>();
        }
    
        public int id { get; set; }
        public int idGroup { get; set; }
        public int idRole { get; set; }
        public string user1 { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public string mLastName { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public bool status { get; set; }
        public string ln_token { get; set; }
        public Nullable<System.DateTime> dtm_fecha_actualizacion { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite_News> Favorite_News { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite_Video> Favorite_Video { get; set; }
    }
}
