//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
            this.User_Video = new HashSet<User_Video>();
            this.Video_TermToSearch = new HashSet<Video_TermToSearch>();
            this.News_Video = new HashSet<News_Video>();
            this.Favorite_Video = new HashSet<Favorite_Video>();
            this.Video_KeyPhrase = new HashSet<Video_KeyPhrase>();
            this.Video_Opinion = new HashSet<Video_Opinion>();
            this.VideoIndexers = new HashSet<VideoIndexer>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> datePublished { get; set; }
        public Nullable<int> idPublisher { get; set; }
        public Nullable<int> idCreator { get; set; }
        public string contentUrl { get; set; }
        public string hostPageUrl { get; set; }
        public Nullable<int> idEncodingFormat { get; set; }
        public string hostPageDisplayUrl { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<System.TimeSpan> duration { get; set; }
        public string embedHtml { get; set; }
        public Nullable<bool> allowHttpsEmbed { get; set; }
        public Nullable<int> viewCount { get; set; }
        public Nullable<int> thumbnailWidth { get; set; }
        public Nullable<int> thumbnailHeight { get; set; }
        public string videoId { get; set; }
        public Nullable<bool> allowMobileEmbed { get; set; }
        public string name { get; set; }
        public string thumbnailUrl { get; set; }
        public string webSearchUrl { get; set; }
        public string motionThumbnailUrl { get; set; }
        public bool status { get; set; }
    
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Video> User_Video { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video_TermToSearch> Video_TermToSearch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News_Video> News_Video { get; set; }
        public virtual Creator Creator { get; set; }
        public virtual EncodingFormat EncodingFormat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite_Video> Favorite_Video { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video_KeyPhrase> Video_KeyPhrase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video_Opinion> Video_Opinion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoIndexer> VideoIndexers { get; set; }
    }
}
