//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_news
    {
        public int id { get; set; }
        public Nullable<int> idCategory { get; set; }
        public Nullable<System.DateTime> datePublished { get; set; }
        public string Expr1 { get; set; }
        public string url { get; set; }
        public string description { get; set; }
        public bool status { get; set; }
        public string text { get; set; }
        public Nullable<double> score { get; set; }
        public Nullable<int> idOpinion { get; set; }
        public string thumbnailContentUrl { get; set; }
        public string contentUrl { get; set; }
        public Nullable<int> thumbnailWidth { get; set; }
        public Nullable<int> thumbnailHeight { get; set; }
        public Nullable<int> idPublisher { get; set; }
        public string Expr2 { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public string Expr4 { get; set; }
        public string Expr5 { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> Expr6 { get; set; }
        public string name { get; set; }
    }
}
