//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_tweets_normalized
    {
        public string Master_Id { get; set; }
        public Nullable<int> Mentions { get; set; }
        public Nullable<int> Hashtags { get; set; }
        public string Tweet { get; set; }
        public string Twitter_Handle { get; set; }
        public string User_Location { get; set; }
        public string User_Number { get; set; }
        public Nullable<double> Sentiment { get; set; }
        public Nullable<double> Sentiment_Bin { get; set; }
        public string Sentiment_Positive_Negative { get; set; }
        public string Language { get; set; }
        public string Account_Tag { get; set; }
    }
}
