//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_tweets_processed
    {
        public string Tweet_Id { get; set; }
        public Nullable<System.DateTime> Original_Date { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Hours { get; set; }
        public Nullable<System.DateTime> Minutes { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Master_Id { get; set; }
        public string Retweet { get; set; }
        public string Username { get; set; }
        public string User_Location { get; set; }
        public string User_Number { get; set; }
        public string Image_URL { get; set; }
        public string Author_Image_URL { get; set; }
        public string Direction { get; set; }
        public Nullable<int> Favorited { get; set; }
        public Nullable<int> User_Followers { get; set; }
        public Nullable<int> User_Friends { get; set; }
        public Nullable<int> User_Favourites { get; set; }
        public Nullable<int> User_Total_Tweets { get; set; }
    }
}
