//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Video
    {
        public string name { get; set; }
        public Nullable<System.TimeSpan> startTime { get; set; }
        public Nullable<System.TimeSpan> endTime { get; set; }
        public Nullable<int> idOpinion { get; set; }
        public Nullable<System.TimeSpan> Expr1 { get; set; }
        public Nullable<System.TimeSpan> Expr2 { get; set; }
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> datePublished { get; set; }
        public Nullable<int> idPublisher { get; set; }
        public Nullable<int> idCreator { get; set; }
        public string contentUrl { get; set; }
        public string hostPageUrl { get; set; }
        public Nullable<int> idEncodingFormat { get; set; }
        public string hostPageDisplayUrl { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<System.TimeSpan> duration { get; set; }
        public string embedHtml { get; set; }
        public Nullable<bool> allowHttpsEmbed { get; set; }
        public Nullable<int> viewCount { get; set; }
        public Nullable<int> thumbnailWidth { get; set; }
        public Nullable<int> thumbnailHeight { get; set; }
        public string videoId { get; set; }
        public Nullable<bool> allowMobileEmbed { get; set; }
        public string Expr3 { get; set; }
        public string thumbnailUrl { get; set; }
        public string webSearchUrl { get; set; }
        public string motionThumbnailUrl { get; set; }
        public string Expr4 { get; set; }
        public string Expr5 { get; set; }
        public string Expr6 { get; set; }
        public string Expr7 { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> Expr8 { get; set; }
        public Nullable<int> idState { get; set; }
        public string idVideoIndexer { get; set; }
        public string url { get; set; }
        public string thumbnail { get; set; }
        public string Expr9 { get; set; }
        public Nullable<int> Expr10 { get; set; }
        public Nullable<int> Expr11 { get; set; }
        public Nullable<int> idGroup { get; set; }
        public string Expr12 { get; set; }
    }
}
