//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int id { get; set; }
        public string contentUrl { get; set; }
        public string thumbnailContentUrl { get; set; }
        public Nullable<int> thumbnailWidth { get; set; }
        public Nullable<int> thumbnailHeight { get; set; }
        public bool status { get; set; }
        public int idNews { get; set; }
    
        public virtual News News { get; set; }
    }
}
